version: '3.3'

networks:
  mynetwork:
    driver: bridge

services:
  # PHP-FPM 
  php:
    build:
      context: ./src/php/
    container_name: php
    expose:
      - "9000"
    volumes:
      - ./src/MenuScanOrder:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - mysql
      - myredis

  # MySQL
  mysql:
    image: mysql:latest
    container_name: sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: MenuScanOrder
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d 
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  # Redis
  myredis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - mynetwork

  # Nginx 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.ini:/etc/nginx/nginx.conf
      - ./src/MenuScanOrder/:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    environment:
      PMA_HOST: mysql 
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql-data:
